<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "dolore".
 *
 * @property int $iddolore
 * @property int $idpazienti
 * @property int $idprocedure
 * @property int $idanestesista
 * @property string|null $orariodolore
 * @property int|null $scaladolore
 *
 * @property User $idanestesista0
 * @property Procedure $idprocedure0
 */
class Dolore extends \yii\db\ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'dolore';

    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['idprocedure', ], 'required'],
            [['idpazienti'], 'safe'],
            [['idprocedure', 'scaladolore'], 'integer'],
            [['orariodolore'], 'string', 'max' => 30],
            [['idprocedure'], 'exist', 'skipOnError' => true, 'targetClass' => Procedure::className(), 'targetAttribute' => ['idprocedure' => 'idprocedure']],
        ];
    }
    public function beforeSave($insert)
    {
        $this->idanestesista = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'iddolore' => 'Iddolore',
            'idprocedure' => 'ID procedura',
            'idanestesista' => 'Idanestesista',
            'idpazienti' => 'ID del paziente',
            'orariodolore' => 'Orario valutazione',
            'scaladolore' => 'VAS',
        ];
    }

    /**
     * Gets query for [[Idanestesista0]].
     *
     * @return \yii\db\ActiveQuery|yii\db\ActiveQuery
     */
    public function getIdanestesista0()
    {
        return $this->hasOne(User::className(), ['id' => 'idanestesista']);
    }

    /**
     * Gets query for [[Idprocedure0]].
     *
     * @return \yii\db\ActiveQuery|ProcedureQuery
     */
    public function getIdprocedure0()
    {
        return $this->hasOne(Procedure::className(), ['idprocedure' => 'idprocedure']);
    }

    public function getIdpazienti(){
        return $this->idprocedure0->idpazienti;
    }

    public function getNomeProcAnestesista() {

        return $this->idprocedure0->nome." ".$this->idprocedure0->cognome;

    }

    /**
     * {@inheritdoc}
     * @return DoloreQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DoloreQuery(get_called_class());
    }
}
